name: ASIC Build Flow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install OpenROAD & Yosys
        run: |
          sudo apt update
          sudo apt install -y \
            openroad yosys magic klayout

      - name: Run Synthesis (Yosys)
        run: |
          yosys -p \
            "read_verilog src/*.v; \
             synth -top TopModule; \
             write_json synth.json"

      - name: Run Floorplanning & Placement (OpenROAD)
        run: |
          openroad -script \
            scripts/floorplan.tcl

      - name: Run Routing
        run: |
          openroad -script \
            scripts/routing.tcl

      - name: Perform DRC & LVS Checks
        run: |
          magic -dnull -noconsole \
            -T techfile.tech \
            scripts/drc_lvs.tcl

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: asic_results
          path: results/
